/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CatatanInteraksi = IDL.Record({
  'isi' : IDL.Text,
  'tanggal' : IDL.Int,
  'ditambahkanOleh' : IDL.Principal,
});
export const JenisPeralatan = IDL.Record({
  'nama' : IDL.Text,
  'deskripsi' : IDL.Text,
  'kategori' : IDL.Text,
});
export const RelasiPelayananMedis = IDL.Record({
  'id' : IDL.Nat,
  'namaFasilitas' : IDL.Text,
  'catatanInteraksi' : IDL.Vec(CatatanInteraksi),
  'email' : IDL.Text,
  'kontakUtama' : IDL.Text,
  'statusKemitraan' : IDL.Text,
});
export const RumahSakitKlinik = IDL.Record({
  'alamat' : IDL.Text,
  'nama' : IDL.Text,
  'kontak' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InventarisPeralatan = IDL.Record({
  'id' : IDL.Nat,
  'jumlah' : IDL.Nat,
  'jenis' : JenisPeralatan,
  'lokasi' : IDL.Text,
});
export const Pengiriman = IDL.Record({
  'id' : IDL.Nat,
  'tujuan' : IDL.Text,
  'status' : IDL.Text,
  'waktuPengiriman' : IDL.Int,
  'peralatan' : IDL.Vec(InventarisPeralatan),
});
export const LaporanRingkasan = IDL.Record({
  'totalPengiriman' : IDL.Nat,
  'totalPeralatan' : IDL.Nat,
  'periodeAkhir' : IDL.Int,
  'pengirimanPerTujuan' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'periodeAwal' : IDL.Int,
});
export const LogPergerakan = IDL.Record({
  'id' : IDL.Nat,
  'jumlah' : IDL.Nat,
  'peralatanId' : IDL.Nat,
  'waktu' : IDL.Int,
  'lokasiAsal' : IDL.Text,
  'lokasiTujuan' : IDL.Text,
  'pengguna' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'nomorKontak' : IDL.Text,
  'nama' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCatatanRelasi' : IDL.Func([IDL.Nat, CatatanInteraksi], [], []),
  'addInventaris' : IDL.Func(
      [JenisPeralatan, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addRelasi' : IDL.Func([RelasiPelayananMedis], [IDL.Nat], []),
  'addRumahSakitKlinik' : IDL.Func([RumahSakitKlinik], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPengiriman' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'deleteInventaris' : IDL.Func([IDL.Nat], [], []),
  'deletePengiriman' : IDL.Func([IDL.Nat], [], []),
  'deleteRelasi' : IDL.Func([IDL.Nat], [], []),
  'deleteRumahSakitKlinik' : IDL.Func([IDL.Text], [], []),
  'generateLaporanByHospital' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(Pengiriman)],
      ['query'],
    ),
  'generateLaporanRingkasan' : IDL.Func(
      [IDL.Int, IDL.Int],
      [LaporanRingkasan],
      ['query'],
    ),
  'getAllInventaris' : IDL.Func([], [IDL.Vec(InventarisPeralatan)], ['query']),
  'getAllLogPergerakan' : IDL.Func([], [IDL.Vec(LogPergerakan)], ['query']),
  'getAllPengiriman' : IDL.Func([], [IDL.Vec(Pengiriman)], ['query']),
  'getAllRelasi' : IDL.Func([], [IDL.Vec(RelasiPelayananMedis)], ['query']),
  'getAllRumahSakitKlinik' : IDL.Func(
      [],
      [IDL.Vec(RumahSakitKlinik)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardData' : IDL.Func(
      [],
      [
        IDL.Record({
          'pendingShipments' : IDL.Nat,
          'totalInventaris' : IDL.Nat,
          'lowStockCount' : IDL.Nat,
          'deliveredShipments' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getInventarisByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InventarisPeralatan)],
      ['query'],
    ),
  'getInventarisById' : IDL.Func([IDL.Nat], [InventarisPeralatan], ['query']),
  'getInventarisByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InventarisPeralatan)],
      ['query'],
    ),
  'getLogByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(LogPergerakan)],
      ['query'],
    ),
  'getLogByEquipmentId' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LogPergerakan)],
      ['query'],
    ),
  'getLowStockItems' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(InventarisPeralatan)],
      ['query'],
    ),
  'getPengirimanByDestination' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Pengiriman)],
      ['query'],
    ),
  'getPengirimanByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Pengiriman)],
      ['query'],
    ),
  'getRelasiById' : IDL.Func([IDL.Nat], [RelasiPelayananMedis], ['query']),
  'getRumahSakitKlinikByName' : IDL.Func(
      [IDL.Text],
      [RumahSakitKlinik],
      ['query'],
    ),
  'getShipmentById' : IDL.Func([IDL.Nat], [Pengiriman], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logPergerakanPeralatan' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInventarisQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updatePengirimanStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateRelasi' : IDL.Func([IDL.Nat, RelasiPelayananMedis], [], []),
  'updateRumahSakitKlinik' : IDL.Func([IDL.Text, RumahSakitKlinik], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CatatanInteraksi = IDL.Record({
    'isi' : IDL.Text,
    'tanggal' : IDL.Int,
    'ditambahkanOleh' : IDL.Principal,
  });
  const JenisPeralatan = IDL.Record({
    'nama' : IDL.Text,
    'deskripsi' : IDL.Text,
    'kategori' : IDL.Text,
  });
  const RelasiPelayananMedis = IDL.Record({
    'id' : IDL.Nat,
    'namaFasilitas' : IDL.Text,
    'catatanInteraksi' : IDL.Vec(CatatanInteraksi),
    'email' : IDL.Text,
    'kontakUtama' : IDL.Text,
    'statusKemitraan' : IDL.Text,
  });
  const RumahSakitKlinik = IDL.Record({
    'alamat' : IDL.Text,
    'nama' : IDL.Text,
    'kontak' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InventarisPeralatan = IDL.Record({
    'id' : IDL.Nat,
    'jumlah' : IDL.Nat,
    'jenis' : JenisPeralatan,
    'lokasi' : IDL.Text,
  });
  const Pengiriman = IDL.Record({
    'id' : IDL.Nat,
    'tujuan' : IDL.Text,
    'status' : IDL.Text,
    'waktuPengiriman' : IDL.Int,
    'peralatan' : IDL.Vec(InventarisPeralatan),
  });
  const LaporanRingkasan = IDL.Record({
    'totalPengiriman' : IDL.Nat,
    'totalPeralatan' : IDL.Nat,
    'periodeAkhir' : IDL.Int,
    'pengirimanPerTujuan' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'periodeAwal' : IDL.Int,
  });
  const LogPergerakan = IDL.Record({
    'id' : IDL.Nat,
    'jumlah' : IDL.Nat,
    'peralatanId' : IDL.Nat,
    'waktu' : IDL.Int,
    'lokasiAsal' : IDL.Text,
    'lokasiTujuan' : IDL.Text,
    'pengguna' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'nomorKontak' : IDL.Text,
    'nama' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCatatanRelasi' : IDL.Func([IDL.Nat, CatatanInteraksi], [], []),
    'addInventaris' : IDL.Func(
        [JenisPeralatan, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addRelasi' : IDL.Func([RelasiPelayananMedis], [IDL.Nat], []),
    'addRumahSakitKlinik' : IDL.Func([RumahSakitKlinik], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPengiriman' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'deleteInventaris' : IDL.Func([IDL.Nat], [], []),
    'deletePengiriman' : IDL.Func([IDL.Nat], [], []),
    'deleteRelasi' : IDL.Func([IDL.Nat], [], []),
    'deleteRumahSakitKlinik' : IDL.Func([IDL.Text], [], []),
    'generateLaporanByHospital' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(Pengiriman)],
        ['query'],
      ),
    'generateLaporanRingkasan' : IDL.Func(
        [IDL.Int, IDL.Int],
        [LaporanRingkasan],
        ['query'],
      ),
    'getAllInventaris' : IDL.Func(
        [],
        [IDL.Vec(InventarisPeralatan)],
        ['query'],
      ),
    'getAllLogPergerakan' : IDL.Func([], [IDL.Vec(LogPergerakan)], ['query']),
    'getAllPengiriman' : IDL.Func([], [IDL.Vec(Pengiriman)], ['query']),
    'getAllRelasi' : IDL.Func([], [IDL.Vec(RelasiPelayananMedis)], ['query']),
    'getAllRumahSakitKlinik' : IDL.Func(
        [],
        [IDL.Vec(RumahSakitKlinik)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardData' : IDL.Func(
        [],
        [
          IDL.Record({
            'pendingShipments' : IDL.Nat,
            'totalInventaris' : IDL.Nat,
            'lowStockCount' : IDL.Nat,
            'deliveredShipments' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getInventarisByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InventarisPeralatan)],
        ['query'],
      ),
    'getInventarisById' : IDL.Func([IDL.Nat], [InventarisPeralatan], ['query']),
    'getInventarisByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InventarisPeralatan)],
        ['query'],
      ),
    'getLogByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(LogPergerakan)],
        ['query'],
      ),
    'getLogByEquipmentId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LogPergerakan)],
        ['query'],
      ),
    'getLowStockItems' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(InventarisPeralatan)],
        ['query'],
      ),
    'getPengirimanByDestination' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Pengiriman)],
        ['query'],
      ),
    'getPengirimanByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Pengiriman)],
        ['query'],
      ),
    'getRelasiById' : IDL.Func([IDL.Nat], [RelasiPelayananMedis], ['query']),
    'getRumahSakitKlinikByName' : IDL.Func(
        [IDL.Text],
        [RumahSakitKlinik],
        ['query'],
      ),
    'getShipmentById' : IDL.Func([IDL.Nat], [Pengiriman], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logPergerakanPeralatan' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInventarisQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updatePengirimanStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateRelasi' : IDL.Func([IDL.Nat, RelasiPelayananMedis], [], []),
    'updateRumahSakitKlinik' : IDL.Func([IDL.Text, RumahSakitKlinik], [], []),
  });
};

export const init = ({ IDL }) => { return []; };