/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CatatanInteraksi {
  'isi' : string,
  'tanggal' : bigint,
  'ditambahkanOleh' : Principal,
}
export interface InventarisPeralatan {
  'id' : bigint,
  'jumlah' : bigint,
  'jenis' : JenisPeralatan,
  'lokasi' : string,
}
export interface JenisPeralatan {
  'nama' : string,
  'deskripsi' : string,
  'kategori' : string,
}
export interface LaporanRingkasan {
  'totalPengiriman' : bigint,
  'totalPeralatan' : bigint,
  'periodeAkhir' : bigint,
  'pengirimanPerTujuan' : Array<[string, bigint]>,
  'periodeAwal' : bigint,
}
export interface LogPergerakan {
  'id' : bigint,
  'jumlah' : bigint,
  'peralatanId' : bigint,
  'waktu' : bigint,
  'lokasiAsal' : string,
  'lokasiTujuan' : string,
  'pengguna' : Principal,
}
export interface Pengiriman {
  'id' : bigint,
  'tujuan' : string,
  'status' : string,
  'waktuPengiriman' : bigint,
  'peralatan' : Array<InventarisPeralatan>,
}
export interface RelasiPelayananMedis {
  'id' : bigint,
  'namaFasilitas' : string,
  'catatanInteraksi' : Array<CatatanInteraksi>,
  'email' : string,
  'kontakUtama' : string,
  'statusKemitraan' : string,
}
export interface RumahSakitKlinik {
  'alamat' : string,
  'nama' : string,
  'kontak' : string,
}
export interface UserProfile { 'nomorKontak' : string, 'nama' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCatatanRelasi' : ActorMethod<[bigint, CatatanInteraksi], undefined>,
  'addInventaris' : ActorMethod<[JenisPeralatan, string, bigint], bigint>,
  'addRelasi' : ActorMethod<[RelasiPelayananMedis], bigint>,
  'addRumahSakitKlinik' : ActorMethod<[RumahSakitKlinik], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPengiriman' : ActorMethod<[string, Array<bigint>], bigint>,
  'deleteInventaris' : ActorMethod<[bigint], undefined>,
  'deletePengiriman' : ActorMethod<[bigint], undefined>,
  'deleteRelasi' : ActorMethod<[bigint], undefined>,
  'deleteRumahSakitKlinik' : ActorMethod<[string], undefined>,
  'generateLaporanByHospital' : ActorMethod<
    [string, bigint, bigint],
    Array<Pengiriman>
  >,
  'generateLaporanRingkasan' : ActorMethod<[bigint, bigint], LaporanRingkasan>,
  'getAllInventaris' : ActorMethod<[], Array<InventarisPeralatan>>,
  'getAllLogPergerakan' : ActorMethod<[], Array<LogPergerakan>>,
  'getAllPengiriman' : ActorMethod<[], Array<Pengiriman>>,
  'getAllRelasi' : ActorMethod<[], Array<RelasiPelayananMedis>>,
  'getAllRumahSakitKlinik' : ActorMethod<[], Array<RumahSakitKlinik>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardData' : ActorMethod<
    [],
    {
      'pendingShipments' : bigint,
      'totalInventaris' : bigint,
      'lowStockCount' : bigint,
      'deliveredShipments' : bigint,
    }
  >,
  'getInventarisByCategory' : ActorMethod<[string], Array<InventarisPeralatan>>,
  'getInventarisById' : ActorMethod<[bigint], InventarisPeralatan>,
  'getInventarisByLocation' : ActorMethod<[string], Array<InventarisPeralatan>>,
  'getLogByDateRange' : ActorMethod<[bigint, bigint], Array<LogPergerakan>>,
  'getLogByEquipmentId' : ActorMethod<[bigint], Array<LogPergerakan>>,
  'getLowStockItems' : ActorMethod<[bigint], Array<InventarisPeralatan>>,
  'getPengirimanByDestination' : ActorMethod<[string], Array<Pengiriman>>,
  'getPengirimanByStatus' : ActorMethod<[string], Array<Pengiriman>>,
  'getRelasiById' : ActorMethod<[bigint], RelasiPelayananMedis>,
  'getRumahSakitKlinikByName' : ActorMethod<[string], RumahSakitKlinik>,
  'getShipmentById' : ActorMethod<[bigint], Pengiriman>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logPergerakanPeralatan' : ActorMethod<
    [bigint, bigint, string, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInventarisQuantity' : ActorMethod<[bigint, bigint], undefined>,
  'updatePengirimanStatus' : ActorMethod<[bigint, string], undefined>,
  'updateRelasi' : ActorMethod<[bigint, RelasiPelayananMedis], undefined>,
  'updateRumahSakitKlinik' : ActorMethod<[string, RumahSakitKlinik], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];