/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CatatanInteraksi {
    isi: string;
    tanggal: bigint;
    ditambahkanOleh: Principal;
}
export interface Pengiriman {
    id: bigint;
    tujuan: string;
    status: string;
    waktuPengiriman: bigint;
    peralatan: Array<InventarisPeralatan>;
}
export interface RumahSakitKlinik {
    alamat: string;
    nama: string;
    kontak: string;
}
export interface LaporanRingkasan {
    totalPengiriman: bigint;
    totalPeralatan: bigint;
    periodeAkhir: bigint;
    pengirimanPerTujuan: Array<[string, bigint]>;
    periodeAwal: bigint;
}
export interface RelasiPelayananMedis {
    id: bigint;
    namaFasilitas: string;
    catatanInteraksi: Array<CatatanInteraksi>;
    email: string;
    kontakUtama: string;
    statusKemitraan: string;
}
export interface LogPergerakan {
    id: bigint;
    jumlah: bigint;
    peralatanId: bigint;
    waktu: bigint;
    lokasiAsal: string;
    lokasiTujuan: string;
    pengguna: Principal;
}
export interface JenisPeralatan {
    nama: string;
    deskripsi: string;
    kategori: string;
}
export interface UserProfile {
    nomorKontak: string;
    nama: string;
}
export interface InventarisPeralatan {
    id: bigint;
    jumlah: bigint;
    jenis: JenisPeralatan;
    lokasi: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCatatanRelasi(id: bigint, catatan: CatatanInteraksi): Promise<void>;
    addInventaris(jenis: JenisPeralatan, lokasi: string, jumlah: bigint): Promise<bigint>;
    addRelasi(relasi: RelasiPelayananMedis): Promise<bigint>;
    addRumahSakitKlinik(facility: RumahSakitKlinik): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPengiriman(tujuan: string, peralatanIds: Array<bigint>): Promise<bigint>;
    deleteInventaris(id: bigint): Promise<void>;
    deletePengiriman(id: bigint): Promise<void>;
    deleteRelasi(id: bigint): Promise<void>;
    deleteRumahSakitKlinik(nama: string): Promise<void>;
    generateLaporanByHospital(namaRumahSakit: string, periodeAwal: bigint, periodeAkhir: bigint): Promise<Array<Pengiriman>>;
    generateLaporanRingkasan(periodeAwal: bigint, periodeAkhir: bigint): Promise<LaporanRingkasan>;
    getAllInventaris(): Promise<Array<InventarisPeralatan>>;
    getAllLogPergerakan(): Promise<Array<LogPergerakan>>;
    getAllPengiriman(): Promise<Array<Pengiriman>>;
    getAllRelasi(): Promise<Array<RelasiPelayananMedis>>;
    getAllRumahSakitKlinik(): Promise<Array<RumahSakitKlinik>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardData(): Promise<{
        pendingShipments: bigint;
        totalInventaris: bigint;
        lowStockCount: bigint;
        deliveredShipments: bigint;
    }>;
    getInventarisByCategory(category: string): Promise<Array<InventarisPeralatan>>;
    getInventarisById(id: bigint): Promise<InventarisPeralatan>;
    getInventarisByLocation(location: string): Promise<Array<InventarisPeralatan>>;
    getLogByDateRange(mulai: bigint, akhir: bigint): Promise<Array<LogPergerakan>>;
    getLogByEquipmentId(peralatanId: bigint): Promise<Array<LogPergerakan>>;
    getLowStockItems(threshold: bigint): Promise<Array<InventarisPeralatan>>;
    getPengirimanByDestination(tujuan: string): Promise<Array<Pengiriman>>;
    getPengirimanByStatus(status: string): Promise<Array<Pengiriman>>;
    getRelasiById(id: bigint): Promise<RelasiPelayananMedis>;
    getRumahSakitKlinikByName(nama: string): Promise<RumahSakitKlinik>;
    getShipmentById(id: bigint): Promise<Pengiriman>;
    getUserProfile(id: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logPergerakanPeralatan(peralatanId: bigint, jumlah: bigint, lokasiAsal: string, lokasiTujuan: string): Promise<bigint>;
    saveCallerUserProfile(profil: UserProfile): Promise<void>;
    updateInventarisQuantity(id: bigint, jumlahBaru: bigint): Promise<void>;
    updatePengirimanStatus(id: bigint, statusBaru: string): Promise<void>;
    updateRelasi(id: bigint, relasiBaru: RelasiPelayananMedis): Promise<void>;
    updateRumahSakitKlinik(nama: string, facility: RumahSakitKlinik): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCatatanRelasi(arg0: bigint, arg1: CatatanInteraksi): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCatatanRelasi(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCatatanRelasi(arg0, arg1);
            return result;
        }
    }
    async addInventaris(arg0: JenisPeralatan, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventaris(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventaris(arg0, arg1, arg2);
            return result;
        }
    }
    async addRelasi(arg0: RelasiPelayananMedis): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRelasi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRelasi(arg0);
            return result;
        }
    }
    async addRumahSakitKlinik(arg0: RumahSakitKlinik): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRumahSakitKlinik(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRumahSakitKlinik(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPengiriman(arg0: string, arg1: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPengiriman(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPengiriman(arg0, arg1);
            return result;
        }
    }
    async deleteInventaris(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventaris(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventaris(arg0);
            return result;
        }
    }
    async deletePengiriman(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePengiriman(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePengiriman(arg0);
            return result;
        }
    }
    async deleteRelasi(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRelasi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRelasi(arg0);
            return result;
        }
    }
    async deleteRumahSakitKlinik(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRumahSakitKlinik(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRumahSakitKlinik(arg0);
            return result;
        }
    }
    async generateLaporanByHospital(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<Pengiriman>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateLaporanByHospital(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateLaporanByHospital(arg0, arg1, arg2);
            return result;
        }
    }
    async generateLaporanRingkasan(arg0: bigint, arg1: bigint): Promise<LaporanRingkasan> {
        if (this.processError) {
            try {
                const result = await this.actor.generateLaporanRingkasan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateLaporanRingkasan(arg0, arg1);
            return result;
        }
    }
    async getAllInventaris(): Promise<Array<InventarisPeralatan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventaris();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventaris();
            return result;
        }
    }
    async getAllLogPergerakan(): Promise<Array<LogPergerakan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLogPergerakan();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLogPergerakan();
            return result;
        }
    }
    async getAllPengiriman(): Promise<Array<Pengiriman>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPengiriman();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPengiriman();
            return result;
        }
    }
    async getAllRelasi(): Promise<Array<RelasiPelayananMedis>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRelasi();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRelasi();
            return result;
        }
    }
    async getAllRumahSakitKlinik(): Promise<Array<RumahSakitKlinik>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRumahSakitKlinik();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRumahSakitKlinik();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardData(): Promise<{
        pendingShipments: bigint;
        totalInventaris: bigint;
        lowStockCount: bigint;
        deliveredShipments: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardData();
            return result;
        }
    }
    async getInventarisByCategory(arg0: string): Promise<Array<InventarisPeralatan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventarisByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventarisByCategory(arg0);
            return result;
        }
    }
    async getInventarisById(arg0: bigint): Promise<InventarisPeralatan> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventarisById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventarisById(arg0);
            return result;
        }
    }
    async getInventarisByLocation(arg0: string): Promise<Array<InventarisPeralatan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventarisByLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventarisByLocation(arg0);
            return result;
        }
    }
    async getLogByDateRange(arg0: bigint, arg1: bigint): Promise<Array<LogPergerakan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogByDateRange(arg0, arg1);
            return result;
        }
    }
    async getLogByEquipmentId(arg0: bigint): Promise<Array<LogPergerakan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogByEquipmentId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogByEquipmentId(arg0);
            return result;
        }
    }
    async getLowStockItems(arg0: bigint): Promise<Array<InventarisPeralatan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockItems(arg0);
            return result;
        }
    }
    async getPengirimanByDestination(arg0: string): Promise<Array<Pengiriman>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengirimanByDestination(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengirimanByDestination(arg0);
            return result;
        }
    }
    async getPengirimanByStatus(arg0: string): Promise<Array<Pengiriman>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengirimanByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengirimanByStatus(arg0);
            return result;
        }
    }
    async getRelasiById(arg0: bigint): Promise<RelasiPelayananMedis> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelasiById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelasiById(arg0);
            return result;
        }
    }
    async getRumahSakitKlinikByName(arg0: string): Promise<RumahSakitKlinik> {
        if (this.processError) {
            try {
                const result = await this.actor.getRumahSakitKlinikByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRumahSakitKlinikByName(arg0);
            return result;
        }
    }
    async getShipmentById(arg0: bigint): Promise<Pengiriman> {
        if (this.processError) {
            try {
                const result = await this.actor.getShipmentById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShipmentById(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logPergerakanPeralatan(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.logPergerakanPeralatan(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logPergerakanPeralatan(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateInventarisQuantity(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventarisQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventarisQuantity(arg0, arg1);
            return result;
        }
    }
    async updatePengirimanStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePengirimanStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePengirimanStatus(arg0, arg1);
            return result;
        }
    }
    async updateRelasi(arg0: bigint, arg1: RelasiPelayananMedis): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRelasi(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRelasi(arg0, arg1);
            return result;
        }
    }
    async updateRumahSakitKlinik(arg0: string, arg1: RumahSakitKlinik): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRumahSakitKlinik(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRumahSakitKlinik(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
